name: Update README (Recent Activity)

on:
  schedule:
    - cron: "0 2 * * *"  # 02:00 UTC ~ 09:00 Asia/Ho_Chi_Minh
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: thientrile
        run: node ./scripts/update_readme.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add README.md
            git commit -m "chore: auto-update recent activity"
            git push
          else
            echo "No changes"
          fi
